pretrain: ./vit-b-16-8f.pt
resume: ""
seed: 1024

data:
    dataset: custom_fall
    modality: RGB
    num_segments: 8
    seg_length: 1
    batch_size: 8
    workers: 4
    num_classes: 12
    image_tmpl: 'img_{:05d}.jpg'

    # 路径保持你的相对路径
    train_list: '../fall_dataset/list_12/train_list.txt'
    val_list:   '../fall_dataset/list_12/val_list.txt'
    label_list: '../fall_dataset/list_12/label_list.csv'

    input_size: 224
    randaug:
        N: 2
        M: 9

network:
    type: clip
    arch: ViT-B/16        # 必须匹配预训练模型
    init: True
    tsm: False
    drop_path_rate: 0.0

    # [关键] 必须是 Transf 才能加载那个 .pt 权重
    sim_header: "Transf"

    joint: False
    describe: False
    drop_out: 0.0
    emb_dropout: 0.0

solver:
    type: cosine
    epochs: 30
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-6
    lr_warmup_step: 5
    momentum: 0.9
    weight_decay: 0.2
    lr_decay_step: 10
    lr_decay_factor: 0.1
    clip_gradient: 20
    loss_type: nll
    eval_freq: 1

    # 👇👇👇 [关键修复] 补上这两行 👇👇👇
    ratio: 1              # 视觉编码器的学习率倍率
    f_ratio: 10           # 时序融合模块的学习率倍率 (通常大一点)

logging:
    print_freq: 10
    eval_freq: 1